version: '3.6'

services:
  quotes-service:
    build: QuotesService
    ports:
      - "3001:3001"
    expose:
      - "3001"
    networks:
      - internalnet
    restart: always
    depends_on:
      - mysqldb
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/


  front-end:
    build: front-end
    ports:
      - "8080:8080"
    environment:
      - "QUOTES_SERVICE_URL=http://quotes-service:3001"
      - "EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/"
    networks:
      - internalnet
    depends_on:
      - quotes-service
      - eureka-server

  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./DatabaseServer/dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: bookclubdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  backend-service:
    build: DatabaseServer
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: bookclubdb
      DB_CONNECTION_LIMIT: 20
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8761/eureka/
    depends_on:
      - mysqldb
      - eureka-server
    networks:
      - internalnet
    

  quiz-service:
    build: QuizService
    ports:
      - "3002:3002"
    expose:
      - "3002"
    networks:
      - internalnet
    restart: always
    depends_on:
      - mysqldb
      - eureka-server
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
   
  eureka-server:
    image: springcloud/eureka
    ports:
      - "8761:8761"
    expose:
      - "8761"
    networks:
      - internalnet
    restart: always

networks:
  internalnet:
    driver: bridge

