version: '3.6'

services:
  quotes-service:
    build: QuotesService
    ports:
      - "3001:3001"
    expose:
      - "3001"
    networks:
      - internalnet
    restart: always
    depends_on:
      - mysqldb


  front-end:
    build: front-end
    ports:
      - "8080:8080"
    networks:
      - internalnet
    depends_on:
      - quotes-service

  mysqldb:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./DatabaseServer/dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./database-data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - 3306
    environment:
      MYSQL_DATABASE: bookclubdb
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: prod
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  backend-service:
    build: DatabaseServer
    ports:
      - "3000:3000"
    expose:
      - "3000"
    environment:
      SERVICE_TAGS: prod
      SERVICE_NAME: nodeappservice
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_USER: 'admin'
      DB_PASSWORD: 'letmein'
      DB_NAME: bookclubdb
      DB_CONNECTION_LIMIT: 20
    depends_on:
      - mysqldb
    networks:
      - internalnet
    
  quiz-service:
    build: QuizService
    ports:
      - "3002:3002"
    expose:
      - "3002"
    networks:
      - internalnet
    restart: always
    depends_on:
      - backend-service   

networks:
  internalnet:
    driver: bridge