version: '3.6'

services:
  quotes-service:
    build: QuotesService
    ports:
      - "3001:3001"
    expose:
      - "3001"
    restart: always
  front-end:
    build: front-end
    ports:
      - "8080:8080"
    environment:
      QUOTES_SERVICE_URL: "http://quotes-service:3001"
    depends_on:
      - quotes-service
