const RECOMMENDATION_QUERY = {
	SELECT_RECOMMENDATIONS_BY_USER: 'SELECT * FROM users WHERE userID = ?',
	CREATE_RECOMMENDATION: 'INSERT INTO recommendations(userID, ISBN) VALUES(?, ?)'
}

export default RECOMMENDATION_QUERY;