const RECOMMENDATION_QUERY = {
	//SELECT_RECOMMENDATIONS_BY_USER: 'SELECT * FROM recommendations WHERE userID = ?',
	SELECT_RECOMMENDATIONS_BY_USER: 'SELECT * FROM books WHERE ISBN IN (SELECT ISBN FROM recommendations WHERE userID = ?)',
	CREATE_RECOMMENDATION: 'INSERT INTO recommendations(userID, ISBN) VALUES(?, ?)'
}

export default RECOMMENDATION_QUERY;