apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quiz
  template:
    metadata:
      labels:
        app: quiz
    spec:
      containers:
        - name: quiz-service
          image: computerkoala/schrodingers-book-club:quiz-service
          ports:
            - containerPort: 3002
---
apiVersion: v1
kind: Service
metadata:
  name: quiz-service
spec:
  selector:
    app: quiz
  ports:
  - protocol: TCP
    port: 3002
    targetPort: 3002
  type: LoadBalancer