apiVersion: apps/v1
kind: Deployment
metadata:
  name: quiz-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: quiz-service
  template:
    metadata:
      labels:
        app: quiz-service
    spec:
      containers:
        - name: quiz-service
          image: computerkoala/schrodingers-book-club:quiz-service
          ports:
            - containerPort: 3002